# -*- coding: utf-8 -*-
"""Newsmatics_hackathon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APOoDrOFdy8HGsIGFThN2K-H5chRA1H4

Download articles by key word
"""

import pandas as pd
import requests
import time


headers = {
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NDA2MzEwODUsInN1YiI6NDU2LCJleHAiOjIwNTU5OTEwODUuMCwic2NvcGVzIjpbImFsbCJdfQ.Hlz5DkbPRbrGYV7hfaIG-Uypzm6h-AGe-4TCITW9PeE",
    "Accept": "application/json"
  }


def api_request(request_url: str):
  url_base = "https://www.newsmatics.com/news-index"
  url = url_base + request_url

  response = requests.get(url, headers=headers)
  return response.json()


def get_keyword_articles(keyword: str) -> pd.DataFrame:
  articles = []

  first_url = f"https://www.newsmatics.com/news-index/api/v1/articles?&page%5Bsize%5D=1000&filter%5Bquery%5D={keyword}&include-ownership=1&include-text=1"

  response = requests.get(first_url, headers=headers).json()
  next_url = response["pagination"]["next"]
  articles.extend(response["articles"])

  while next_url is not None:
    print(next_url)
    time.sleep(0.1)
    next_url = next_url + "&include-ownership=1&include-text=1"
    response = api_request(next_url)
    articles.extend(response["articles"])
    next_url = response["pagination"].get("next", None)

  return pd.DataFrame(articles)


key_word = "boeing"
df = get_keyword_articles(key_word)
df.to_csv(key_word + ".csv")

"""Sentiment analysis"""

from transformers import AutoModelForSequenceClassification, AutoTokenizer
import torch
from tqdm import tqdm
import random
import pandas as pd

torch.cuda.empty_cache()
# !nvidia-smi

tqdm.pandas()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load model and tokenizer
model_name = "yangheng/deberta-v3-base-absa-v1.1"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)

def analyze_aspect_sentiment(sentence, aspect):
    # Format the input with aspect
    aspect_sentence = f"{sentence} [ASP] {aspect}"

    # Tokenize input
    inputs = tokenizer(aspect_sentence, return_tensors="pt", padding=True, truncation=True).to(device)

    # Perform inference
    with torch.no_grad():
        outputs = model(**inputs)

    # Get sentiment prediction
    predictions = torch.argmax(outputs.logits, dim=-1).item()
    predictions_softmax = torch.softmax(outputs.logits, dim=-1).tolist()[0]

    # Map predictions to sentiment labels
    sentiment_labels = ["negative", "neutral", "positive"]
    return sentiment_labels[predictions], predictions_softmax[0], predictions_softmax[1], predictions_softmax[2]


def give_sentiment_aspect(df, aspect):
  # df = df.copy().sample(frac=0.5).reset_index(drop=True)
  df = df[df['text'].str.len() <= 10000]
  print(len(df))

  df.loc[:, ["sentiment_label", "negative_score", "neutral_score", "positive_score"]] = df["text"].progress_apply(
        lambda x: pd.Series(analyze_aspect_sentiment(x, aspect))
    ).values

  df = df[df["sentiment_label"].notnull()]

  return df.copy()


df_sentiment = give_sentiment_aspect(df, key_word)
df_sentiment = df_sentiment.dropna()
df_sentiment.to_csv(key_word + "_sentiment.csv")

df_sentiment.head(4)